language: python

services:
  - docker

before_install:
- docker pull mergermarket/cdflow-commands

before_script:
- git checkout git@github.com:mergermarket/svcs-platform-config.git platform-config
- pip install cdflow

script:
- cdflow --help