version: 2.1
description: test deployment in circeci

orbs:
  cdflow: acuris/cdflow@dev:cache

workflows:
  test-pipeline:
    jobs:
      - cdflow/release:
          platform-config: test-platform-config
          context: DevTeam-Platform
      - cdflow/deploy:
          env: aslive
          requires: 
            - cdflow/release
          context: DevTeam-Platform
