version: 2
jobs:
  get_cdflow:
    docker:
      - image: python
    steps:
      - run: 
          name: Get cdflow
          command: pip install cdflow
  do_release:
    machine: 
      image: circleci/classic:201708-01
    steps:
      - checkout
      - run:
          name: Run Release 
          command: cdflow --help
            
workflows:
  version: 2
  cdflow:
    jobs:
      - get_cdflow
      - do_release:
          requires:
            -  get_cdflow
          context: DevTeam-Platform
