version: 2
jobs:
  get_cdflow:
    steps:
      - checkout 
      - run: 
          name: Get cdflow
          command: pip install cdflow
workflows:
  version: 2
  cdflow:
    jobs:
      - get_cdflow:
          context: DevTeam-Platform
