version: 2
jobs:
  get_cdflow:
    machine: 
      image: circleci/classic:201708-01
    steps:
      - run: 
          name: Get cdflow
          command: pip install cdflow awscli
      - checkout
      - git clone https://github.com/mergermarket/test-platform-config.git platform-config
      - run:
          name: Run Release 
          command: |
            cdflow release --platform-config ./platform-config 1-keir -v 
workflows:
  version: 2
  cdflow:
    jobs:
      - get_cdflow:
          context: DevTeam-Platform
