version: 2

executors:
  my_exec:
    machine: 
      - image: circleci/classic:latest
jobs:
  get_cdflow:
    executor: my_exec
    steps:
      - run: 
          name: Get cdflow
          command: |
            env
            python --version
            pip install cdflow awscli
      - checkout
      - run:
          name: Get Platform Config
          command: git clone https://github.com/mergermarket/test-platform-config.git platform-config

  run_cdflow:
    executor: my_exec
    steps:
      - run:
          name: Run Release 
          command: |
            cdflow release --platform-config ./platform-config 1-keir -v 
workflows:
  version: 2
  cdflow:
    jobs:
      - get_cdflow:
          context: DevTeam-Platform
      - run_cdflow:
          context: DevTeam-Platform
