version: 2
jobs:
  get_cdflow:
    machine: 
      image: circleci/classic:201708-01
    steps:
      - run: 
          name: Get cdflow
          command: pip install cdflow
      - checkout
      - run:
          name: Run Release 
          command: cdflow --help
            
workflows:
  version: 2
  cdflow:
    jobs:
      - get_cdflow:
          context: DevTeam-Platform
