version: 2.1

executors:
  my-exec:
    machine: 
      image: circleci/classic:latest
jobs:
  get_cdflow:
    executor: my-exec
    steps:
      - checkout
      - run: 
          name: Get cdflow
          command: |
            python --version
            pip install pipenv
            export WORKON_HOME=~/.venvs
            pipenv install cdflow
            pwd
            ls -l
            find .
      - run:
          name: Get Platform Config
          command: |
            ls -l
            find .
            rm -rf platform-config
            git clone https://github.com/mergermarket/test-platform-config.git platform-config
      - save_cache:
          paths:
            - ~/.venvs
            - /usr/local/bin/cdflow
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}      

  run_cdflow:
    executor: my-exec
    steps:
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip-packages-v1-{{ .Branch }}-
            - pip-packages-v1-
      - run:
          name: Run Release 
          command: |
            cdflow release --platform-config ./platform-config 1-keir -v 
workflows:
  version: 2.1
  cdflow:
    jobs:
      - get_cdflow:
          context: DevTeam-Platform
      - run_cdflow:
          context: DevTeam-Platform
          requires: 
            - get_cdflow
