version: 2
jobs:
  get_cdflow:
    machine: 
      image: circleci/classic:201708-01
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    steps:
      - run: 
          name: Get cdflow
          command: pip install cdflow awscli
      - checkout
      - run:
          name: Run Release 
          command: aws s3 ls
            
workflows:
  version: 2
  cdflow:
    jobs:
      - get_cdflow:
          context: DevTeam-Platform
