version: 2.1
description: cdflow orb

orbs:
  cdflow:
    executors:
      cdflow-exec:
        machine: 
          image: circleci/classic:latest
    commands:
      install-cdflow:
        steps:
          - restore_cache:
              keys:
                # when lock file changes, use increasingly general patterns to restore cache
                - pip-packages-v6-{{ .Branch }}-
                - pip-packages-v6-
          - run: 
              name: Get cdflow
              command: |
                pyenv global 3.5.2
                pip3 install cdflow
          - save_cache:
              paths:
                - /opt/circleci/.pyenv/
              key: pip-packages-v6-{{ .Branch }}-{{ checksum "/opt/circleci/.pyenv/shims/cdflow" }}         
      get-platform-config:
        steps:
          - run:
              name: Get Platform Config
              command: |
                git clone https://github.com/mergermarket/test-platform-config.git platform-config
    
    jobs:
      release:
        executor: cdflow-exec
        steps:
          - checkout
          - get-platform-config
          - install-cdflow
          - run:
              name: Run Release 
              command: |
                pyenv global 3.5.2
                cdflow release --platform-config ./platform-config 1-keir -v 
      plan:
        executor: cdflow-exec
        steps:
          - checkout
          - install-cdflow
          - run:
              name: Run Release 
              command: |
                pyenv global 3.5.2
                cdflow deploy 1-keir -v -p


workflows:
  version: 2.1
  cdflow:
    jobs:
      - cdflow/release
      - cdflow/plan
          