version: 2.1

executors:
  my-exec:
    machine: 
      image: circleci/classic:latest
jobs:
  get_cdflow:
    executor: my-exec
    steps:
      - checkout
      - run: 
          name: Get cdflow
          command: |
            pyenv versions
            pyenv global 3.5.2
            python3 --version
            pip3 install cdflow
            # export WORKON_HOME=~/.venvs
            # pipenv install cdflow
            cdflow --help
      - run:
          name: Get Platform Config
          command: |
            git clone https://github.com/mergermarket/test-platform-config.git platform-config
      - save_cache:
          paths:
            - /opt/circleci/.pyenv/versions/3.5.2/
            - /usr/local/bin/cdflow
          key: pip-packages-v4-{{ .Branch }}-{{ checksum "Pipfile.lock" }}      

  run_cdflow:
    executor: my-exec
    steps:
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip-packages-v4-{{ .Branch }}-
            - pip-packages-v4-
      - run:
          name: Run Release 
          command: |
            pip list 
            ls -l /usr/local/bin/c*
            echo "------------"
            ls -l
            cdflow release --platform-config ./platform-config 1-keir -v 
workflows:
  version: 2.1
  cdflow:
    jobs:
      - get_cdflow:
          context: DevTeam-Platform
      - run_cdflow:
          context: DevTeam-Platform
          requires: 
            - get_cdflow
