name: CDFLOW Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get cdflow-commands
      run: |
        docker pull mergermarket/cdflow-commands

    - name: install cdflow
      run: |
        sudo pip install cdflow
        cdflow --help
  

